<Project Sdk="Microsoft.NET.Sdk">

  <!-- Place this at the very top of your .csproj or in Directory.Build.props -->
  <PropertyGroup Condition="'$(BuildThisProject)' != 'true'">
    <Configuration>None</Configuration>
    <IsPrimaryProject>false</IsPrimaryProject>
    <SkipCopyBuildProduct>true</SkipCopyBuildProduct>
  </PropertyGroup>

  <!-- This strips the core source file array out before MSBuild hits the compiler -->
  <ItemGroup Condition="'$(BuildThisProject)' != 'true'">
    <Compile Remove="**\*.cs" />
    <EmbeddedResource Remove="**\*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\dj.test\dj.test.csproj" />
    <ProjectReference Include="../../src/shared/shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.16.0-preview.1" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <RootNamespace>benchmark_cli</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Update="../../reference/**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
