<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <RootNamespace>dj.test.system</RootNamespace>
    <TargetFramework>net11.0</TargetFramework>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="8.10.0" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="11.0.0-preview.5.26302.115" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="11.0.0-preview.5.26302.115"/> 
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\shared\shared.csproj" />
    <ProjectReference Include="..\..\src\api.core\api.core.csproj" />
    <ProjectReference Include="..\..\src\api\api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../reference/**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="appsettings*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
