<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Dapper.Contrib" Version="2.0.78" />
    <PackageReference Include="Dapper.Logging" Version="0.4.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.9" />
  <!-- Force the background dependency to use the latest safe version -->
  <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
  
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="10.0.9" />
    <PackageReference Include="RestSharp" Version="114.0.0" />
    <PackageReference Include="Syn.WordNet" Version="1.0.5" />
    <PackageReference Include="System.Threading.RateLimiting" Version="10.0.9" />
    <PackageReference Include="WeCantSpell.Hunspell" Version="7.0.1" />
  </ItemGroup>
<ItemGroup>
  <EmbeddedResource Include="data\sql\CreateDatabase.sql" />  
  <EmbeddedResource Include="data\sql\TruncateDatabase.sql" />
  <EmbeddedResource Include="TMDB\sql\TMDB_Create.sql" />
  <EmbeddedResource Include="TMDB\sql\TMDB_Truncate.sql" />
</ItemGroup>
<ItemGroup>
    <None Include="dic/*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="../../reference/**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
</ItemGroup>
</Project>
