@api_HostAddress = http://localhost:5282

GET {{api_HostAddress}}/health
Accept: application/json
###

GET {{api_HostAddress}}/token/anonymous
Accept: application/json
###

GET {{api_HostAddress}}/api/media/search?query=training,day
Accept: application/json

###

GET {{api_HostAddress}}/api/media/query?query=training,day
Accept: application/json

###

GET {{api_HostAddress}}/api/media/details?query=training,day
Accept: application/json
###

GET {{api_HostAddress}}/api/media/media?type=Video&updateRepo=true
Accept: application/json
###

GET {{api_HostAddress}}/api/media/match/local?query=dirty,cop&type=Video&minimumHits=1
Accept: application/json
###

GET {{api_HostAddress}}/api/media/match/local/synonyms?query=dirty,cop&type=Video&minimumHits=1
Accept: application/json
###

POST {{api_HostAddress}}/api/media/update/?fromScratch=true&baseDirectory=//fatty/existing
Accept: application/json
###

GET {{api_HostAddress}}/api/media/update/status/
Accept: application/json
###

POST {{api_HostAddress}}/api/media/update/cancel
Accept: application/json
###

POST {{api_HostAddress}}/api/media/tmdb/update
Accept: application/json
###

POST {{api_HostAddress}}/api/media/tmdb/update/cancel
Accept: application/json
###

GET {{api_HostAddress}}/api/media/tmdb/update/status
Accept: application/json
###