<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>021f742e-d3d2-4845-bd80-df4808e1bf83</UserSecretsId>  
    <IsTestProject>false</IsTestProject>
    <IsTestingPlatformApplication>false</IsTestingPlatformApplication>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
    <PackageReference Include="OpenIddict" Version="7.6.0" />
    <PackageReference Include="OpenIddict.AspNetCore" Version="7.6.0" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="7.6.0" />
    <PackageReference Include="OpenIddict.Server.AspNetCore" Version="7.6.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\shared\shared.csproj" />
    <ProjectReference Include="..\api.core\api.core.csproj" />
  </ItemGroup>
</Project>
